# Generated by Django 5.0.2 on 2024-02-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
