# Generated by Django 5.0.2 on 2024-02-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantassignment',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
