# Generated by Django 5.0.2 on 2024-02-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_tenantassignment_property_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantAssignment',
            new_name='TenantAgreement',
        ),
    ]
